### ISSUE TITLE
生成so 文件之后，在all moudule 里面找不到so

### ISSUE THREAD

**Issue by 704480904** [phynos/Scanner#2]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.east.scanner-nxY7eK9Vu9pdUz80jH8SRQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.east.scanner-nxY7eK9Vu9pdUz80jH8SRQ==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libiconv.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.dtr.zxing.activity.CaptureActivity.<clinit>(CaptureActivity.java:147)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)

**Comment by phynos** [comment]
默认只生产了arm-v7的so，如果要生成其他的，可以修改编译文件

**Comment by phynos** [comment]
已经改为cmake，更为通用
